package model.entity;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;

import oracle.jdbc.OracleTypes;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 25 22:55:54 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpProcessInfoEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        UnitProcessId {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getUnitProcessId();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setUnitProcessId((Number)value);
            }
        }
        ,
        ProcessName {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getProcessName();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setProcessName((String)value);
            }
        }
        ,
        WpSectionId {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getWpSectionId();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setWpSectionId((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        WpProcessId {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getWpProcessId();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setWpProcessId((Number)value);
            }
        }
        ,
        UnitSectionId {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getUnitSectionId();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setUnitSectionId((Number)value);
            }
        }
        ,
        WpSectionInfoEO {
            public Object get(WpProcessInfoEOImpl obj) {
                return obj.getWpSectionInfoEO();
            }

            public void put(WpProcessInfoEOImpl obj, Object value) {
                obj.setWpSectionInfoEO((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WpProcessInfoEOImpl object);

        public abstract void put(WpProcessInfoEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UNITPROCESSID = AttributesEnum.UnitProcessId.index();
    public static final int PROCESSNAME = AttributesEnum.ProcessName.index();
    public static final int WPSECTIONID = AttributesEnum.WpSectionId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int WPPROCESSID = AttributesEnum.WpProcessId.index();
    public static final int UNITSECTIONID = AttributesEnum.UnitSectionId.index();
    public static final int WPSECTIONINFOEO = AttributesEnum.WpSectionInfoEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WpProcessInfoEOImpl() {
    }
    private Number getNewUnitProcessId() {

           Number newUnitProcessId = null;
           String stmt = "BEGIN :1 := APPS.WP_NEW_UNIT_PROCESS_ID(:2)  ; end;";

           java.sql.CallableStatement cs =
               getDBTransaction().createCallableStatement(stmt, 1);

           //        System.out.println("Level 2 Procedure 2 ");

           try {
               cs.registerOutParameter(1, OracleTypes.VARCHAR);
               cs.setObject(2, this.getWpSectionId());
               cs.execute();
               newUnitProcessId = new Number(cs.getString(1));
               cs.close();
           } catch (Exception e) {
               e.printStackTrace();
           }
           return newUnitProcessId;


       }
    /**
     * Gets the attribute value for UnitProcessId, using the alias name UnitProcessId.
     * @return the UnitProcessId
     */
    public Number getUnitProcessId() {
        return (Number)getAttributeInternal(UNITPROCESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitProcessId.
     * @param value value to set the UnitProcessId
     */
    public void setUnitProcessId(Number value) {
        setAttributeInternal(UNITPROCESSID, value);
    }

    /**
     * Gets the attribute value for ProcessName, using the alias name ProcessName.
     * @return the ProcessName
     */
    public String getProcessName() {
        return (String)getAttributeInternal(PROCESSNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProcessName.
     * @param value value to set the ProcessName
     */
    public void setProcessName(String value) {
        setAttributeInternal(PROCESSNAME, value);
    }

    /**
     * Gets the attribute value for WpSectionId, using the alias name WpSectionId.
     * @return the WpSectionId
     */
    public Number getWpSectionId() {
        return (Number)getAttributeInternal(WPSECTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WpSectionId.
     * @param value value to set the WpSectionId
     */
    public void setWpSectionId(Number value) {
        setAttributeInternal(WPSECTIONID, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for WpProcessId, using the alias name WpProcessId.
     * @return the WpProcessId
     */
    public Number getWpProcessId() {
        return (Number)getAttributeInternal(WPPROCESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WpProcessId.
     * @param value value to set the WpProcessId
     */
    public void setWpProcessId(Number value) {
        setAttributeInternal(WPPROCESSID, value);
    }

    /**
     * Gets the attribute value for UnitSectionId, using the alias name UnitSectionId.
     * @return the UnitSectionId
     */
    public Number getUnitSectionId() {
        return (Number)getAttributeInternal(UNITSECTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitSectionId.
     * @param value value to set the UnitSectionId
     */
    public void setUnitSectionId(Number value) {
        setAttributeInternal(UNITSECTIONID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getWpSectionInfoEO() {
        return (EntityImpl)getAttributeInternal(WPSECTIONINFOEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setWpSectionInfoEO(EntityImpl value) {
        setAttributeInternal(WPSECTIONINFOEO, value);
    }

    /**
     * @param wpProcessId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number wpProcessId) {
        return new Key(new Object[]{wpProcessId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.WpProcessInfoEO");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
              String orgId = (String)sessionScope.get("orgId");
              
              super.create(attributeList);
              
         //     if(orgId.equals("344")) {
              oracle.jbo.server.SequenceImpl s =
                  new oracle.jbo.server.SequenceImpl("WP_PROCESS_INFO_SEQ",
                                                     getDBTransaction());
              oracle.jbo.domain.Number sVal = s.getSequenceNumber();
              
              this.setWpProcessId(sVal);
              
           //   }
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();
               String user = (String)sessionScope.get("userId");
               
               //        System.out.println("Document No -->" + getSrNoString());
                
               if (DML_UPDATE == operation) {
                   try {
                       setLastUpdatedDate((Date)Date.getCurrentDate());
                       setLastUpdatedBy(new oracle.jbo.domain.Number(user));              
                       
                   } catch (SQLException f) {
                       f.printStackTrace();
                   }
               } else if (DML_INSERT == operation) {               
                       try {                    
                             if(this.getUnitProcessId() == null ){  // not populated from popup
                               this.setUnitProcessId(this.getNewUnitProcessId());
                           }
                       this.setUnitSectionId((Number)this.getWpSectionInfoEO().getAttribute("UnitSectionId"));             
                       setCreationDate((Date)Date.getCurrentDate());
                       setCreatedBy(new oracle.jbo.domain.Number(user));

                   } catch (SQLException f) {
                       f.printStackTrace();
                   }
              
                    
                  
               }
            super.doDML(operation, e);
    }
}
