package model.view;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 23 16:28:56 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SectionInfoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SectionInfoVOImpl() {
    }

  
}
