package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 25 22:56:26 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpProcessInfoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WpProcessInfoVOImpl() {
    }
}
