package model.view;

import model.entity.WpSectionInfoEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 23 16:35:24 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpSectionInfoVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        SectionId {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getSectionId();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setSectionId((Number)value);
            }
        }
        ,
        SectionName {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getSectionName();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setSectionName((String)value);
            }
        }
        ,
        OrgId {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        CostCenter {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getCostCenter();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setCostCenter((String)value);
            }
        }
        ,
        Serial {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getSerial();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setSerial((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        OrgName {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getOrgName();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setOrgName((String)value);
            }
        }
        ,
        WpProcessInfoVO {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getWpProcessInfoVO();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OrgVO1 {
            public Object get(WpSectionInfoVORowImpl obj) {
                return obj.getOrgVO1();
            }

            public void put(WpSectionInfoVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WpSectionInfoVORowImpl object);

        public abstract void put(WpSectionInfoVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SECTIONID = AttributesEnum.SectionId.index();
    public static final int SECTIONNAME = AttributesEnum.SectionName.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int COSTCENTER = AttributesEnum.CostCenter.index();
    public static final int SERIAL = AttributesEnum.Serial.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ORGNAME = AttributesEnum.OrgName.index();
    public static final int WPPROCESSINFOVO = AttributesEnum.WpProcessInfoVO.index();
    public static final int ORGVO1 = AttributesEnum.OrgVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WpSectionInfoVORowImpl() {
    }

    /**
     * Gets WpSectionInfoEO entity object.
     * @return the WpSectionInfoEO
     */
    public WpSectionInfoEOImpl getWpSectionInfoEO() {
        return (WpSectionInfoEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for SECTION_ID using the alias name SectionId.
     * @return the SECTION_ID
     */
    public Number getSectionId() {
        return (Number) getAttributeInternal(SECTIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SECTION_ID using the alias name SectionId.
     * @param value value to set the SECTION_ID
     */
    public void setSectionId(Number value) {
        setAttributeInternal(SECTIONID, value);
    }

    /**
     * Gets the attribute value for SECTION_NAME using the alias name SectionName.
     * @return the SECTION_NAME
     */
    public String getSectionName() {
        return (String) getAttributeInternal(SECTIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for SECTION_NAME using the alias name SectionName.
     * @param value value to set the SECTION_NAME
     */
    public void setSectionName(String value) {
        setAttributeInternal(SECTIONNAME, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for COST_CENTER using the alias name CostCenter.
     * @return the COST_CENTER
     */
    public String getCostCenter() {
        return (String) getAttributeInternal(COSTCENTER);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_CENTER using the alias name CostCenter.
     * @param value value to set the COST_CENTER
     */
    public void setCostCenter(String value) {
        setAttributeInternal(COSTCENTER, value);
    }

    /**
     * Gets the attribute value for SERIAL using the alias name Serial.
     * @return the SERIAL
     */
    public Number getSerial() {
        return (Number) getAttributeInternal(SERIAL);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIAL using the alias name Serial.
     * @param value value to set the SERIAL
     */
    public void setSerial(Number value) {
        setAttributeInternal(SERIAL, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgName.
     * @return the OrgName
     */
    public String getOrgName() {
        String orgName = (String)this.getOrgVO1().first().getAttribute("OrgName");
        return orgName;
       // return (String) getAttributeInternal(ORGNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgName.
     * @param value value to set the  OrgName
     */
    public void setOrgName(String value) {
        setAttributeInternal(ORGNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WpProcessInfoVO.
     */
    public RowIterator getWpProcessInfoVO() {
        return (RowIterator)getAttributeInternal(WPPROCESSINFOVO);
    }


    /**
     * Gets the view accessor <code>RowSet</code> OrgVO1.
     */
    public RowSet getOrgVO1() {
        return (RowSet)getAttributeInternal(ORGVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
